import React, { createContext, useContext, useState, useEffect } from 'react';
import { getSettings, updateSettings } from '@/utils/storage';

type LanguageContextType = {
  language: 'ar' | 'en' | 'fr';
  setLanguage: (language: 'ar' | 'en' | 'fr') => void;
  t: (key: string) => string;
};

const translations = {
  ar: {
    // General
    "all_products": "كل المنتجات",
    "no_products_in_category": "لا توجد منتجات في هذا التصنيف",
    "no_categories_available": "لا توجد تصنيفات متاحة",
    "settings": "الإعدادات",
    "save_settings": "حفظ الإعدادات",
    "general": "عام",
    "printing": "الطباعة",
    "business": "معلومات المتجر",
    "search_products": "البحث عن منتجات...",

    // Settings
    "general_settings": "إعدادات عامة",
    "auto_print_receipt": "طباعة تلقائية للفواتير",
    "auto_print_receipt_desc": "طباعة الفاتورة تلقائياً عند إتمام الطلب",
    "auto_kitchen_print": "طباعة تلقائية للمطبخ",
    "auto_kitchen_print_desc": "إرسال الطلب تلقائياً للطباعة في المطبخ",
    "show_price_kitchen": "عرض الأسعار في شاشة المطبخ",
    "show_price_kitchen_desc": "عرض أسعار المنتجات في شاشة المطبخ",
    "app_language": "لغة البرنامج",
    "app_language_desc": "اختر لغة واجهة المستخدم",
    "currency_symbol": "رمز العملة",
    "arabic": "العربية",
    "english": "English",
    "french": "Français",
    "choose_language": "اختر اللغة",

    // Printing settings
    "printing_settings": "إعدادات الطباعة",
    "receipt_printer": "طابعة الفواتير",
    "kitchen_printer": "طابعة المطبخ",
    "choose_printer": "اختر طابعة",
    "default_printer": "الطابعة الافتراضية",
    "thermal_printer": "طابعة حرارية",
    "receipt_width": "عرض الفاتورة (مم)",
    "show_logo": "عرض الشعار في الفاتورة",

    // Business settings
    "business_info": "معلومات المتجر",
    "business_name": "اسم المتجر",
    "business_address": "عنوان المتجر",
    "business_phone": "رقم الهاتف",
    "tax_rate": "نسبة الضريبة (%)",
    "receipt_footer": "نص أسفل الفاتورة",

    // Error messages
    "no_permission": "لا تملك صلاحية تعديل الإعدادات",
    "settings_saved": "تم حفظ الإعدادات بنجاح",
    "settings_error": "حدث خطأ أثناء حفظ الإعدادات",
    "unauthorized": "غير مصرح",
    "no_access": "ليس لديك صلاحية الوصول إلى إعدادات النظام",

    // Navigation and menu items
    "dashboard": "لوحة التحكم",
    "cashier": "الكاشير",
    "kitchen": "المطبخ",
    "admin": "الإدارة",
    "reports": "التقارير",
    "products": "المنتجات",
    "queue": "قائمة الانتظار",
    "logout": "تسجيل خروج",

    // Login page
    "login": "تسجيل الدخول",
    "username": "اسم المستخدم",
    "password": "كلمة المرور",
    "show_password": "إظهار كلمة المرور",
    "hide_password": "إخفاء كلمة المرور",
    "sign_in": "دخول",
    "invalid_credentials": "بيانات الدخول غير صحيحة",

    // Order management
    "new_order": "طلب جديد",
    "current_order": "الطلب الحالي",
    "add_to_order": "إضافة للطلب",
    "remove_from_order": "إزالة من الطلب",
    "complete_order": "إتمام الطلب",
    "cancel_order": "إلغاء الطلب",
    "order_total": "إجمالي الطلب",
    "subtotal": "المجموع الفرعي",
    "tax": "الضريبة",
    "discount": "خصم",
    "total": "الإجمالي",

    // Payment
    "payment": "الدفع",
    "cash": "نقداً",
    "card": "بطاقة",
    "amount_paid": "المبلغ المدفوع",
    "change": "الباقي",

    // Product management
    "add_product": "إضافة منتج",
    "edit_product": "تعديل منتج",
    "delete_product": "حذف منتج",
    "product_name": "اسم المنتج",
    "product_price": "سعر المنتج",
    "product_category": "فئة المنتج",
    "available": "متوفر",
    "unavailable": "غير متوفر",

    // Categories
    "categories": "التصنيفات",
    "add_category": "إضافة تصنيف",
    "category_name": "اسم التصنيف",
    "edit_category": "تعديل التصنيف",
    "delete_category": "حذف التصنيف",

    // Actions
    "add": "إضافة",
    "edit": "تعديل",
    "delete": "حذف",
    "save": "حفظ",
    "cancel": "إلغاء",
    "confirm": "تأكيد",
    "close": "إغلاق",
    "back": "رجوع",
    "next": "التالي",
    "previous": "السابق",
    "submit": "إرسال",
    "reset": "إعادة تعيين",
    "clear": "مسح",
    "refresh": "تحديث",
    "search": "بحث",
    "filter": "تصفية",
    "sort": "ترتيب",
    "view": "عرض",
    "print": "طباعة",
    "download": "تحميل",
    "upload": "رفع",
    "import": "استيراد",
    "export": "تصدير",

    // Status
    "active": "نشط",
    "inactive": "غير نشط",
    "enabled": "مفعل",
    "disabled": "معطل",
    "online": "متصل",
    "offline": "غير متصل",
    "loading": "جاري التحميل...",
    "saving": "جاري الحفظ...",
    "success": "نجح",
    "error": "خطأ",
    "warning": "تحذير",
    "info": "معلومات",

    // Common phrases
    "welcome": "مرحباً",
    "goodbye": "وداعاً",
    "hello": "أهلاً",
    "thank_you": "شكراً لك",
    "please": "من فضلك",
    "yes": "نعم",
    "no": "لا",
    "ok": "موافق",
    "maybe": "ربما",
    "sure": "بالتأكيد",
    "definitely": "بالتأكيد",
    "probably": "على الأرجح",
    "possibly": "ربما",

    // Missing translations
    "no_items_in_order": "لا توجد عناصر في الطلب",
    "order_summary": "ملخص الطلب",
    "proceed_to_payment": "المتابعة للدفع",
    "users": "المستخدمون",
    "user_management": "إدارة المستخدمين",
    "add_user": "إضافة مستخدم",
    "edit_user": "تعديل مستخدم",
    "delete_user": "حذف مستخدم",
    "role": "الدور الوظيفي",
    "permissions": "الصلاحيات",
    "status": "الحالة",
    "last_login": "آخر تسجيل دخول",
    "created_date": "تاريخ الإنشاء",
    "user_details": "تفاصيل المستخدم",
    "select_role": "اختر الدور",
    "password_confirm": "تأكيد كلمة المرور",
    "passwords_not_match": "كلمات المرور غير متطابقة",
    "user_created": "تم إنشاء المستخدم بنجاح",
    "user_updated": "تم تحديث المستخدم بنجاح",
    "user_deleted": "تم حذف المستخدم بنجاح",
    "confirm_delete_user": "هل أنت متأكد من حذف هذا المستخدم؟",
    "manage_orders_and_status": "إدارة الطلبات وحالات التحضير",
    "pending_orders": "الطلبات المعلقة",
    "in_progress": "قيد التحضير",
    "ready": "جاهز",
    "completed": "مكتمل",
    "cancelled": "ملغي",
    "order_number": "رقم الطلب",
    "order_time": "وقت الطلب",
    "customer": "العميل",
    "items_count": "عدد العناصر",
    "mark_as_ready": "تحديد كجاهز",
    "mark_as_completed": "تحديد كمكتمل",
    "view_details": "عرض التفاصيل",

    // Additional missing translations
    "grand_total": "الإجمالي النهائي",
    "item": "عنصر",
    "items": "عناصر",
    "quantity": "الكمية",
    "price": "السعر",
    "amount": "المبلغ",
    "description": "الوصف",
    "note": "ملاحظة",
    "notes": "ملاحظات",
    "customer_name": "اسم العميل",
    "table_number": "رقم الطاولة",
    "order_type": "نوع الطلب",
    "dine_in": "تناول في المكان",
    "takeaway": "طلب خارجي",
    "delivery": "توصيل",
    "apply_discount": "تطبيق خصم",
    "discount_percentage": "نسبة الخصم",
    "discount_amount": "مبلغ الخصم",
    "apply": "تطبيق",
    "remove_discount": "إزالة الخصم",
    "payment_method": "طريقة الدفع",
    "cash_payment": "دفع نقدي",
    "card_payment": "دفع بالبطاقة",
    "split_payment": "تقسيم الدفع",
    "received_amount": "المبلغ المستلم",
    "change_amount": "مبلغ الفكة",
    "print_receipt": "طباعة الفاتورة",
    "send_to_kitchen": "إرسال للمطبخ",
    "order_placed": "تم وضع الطلب",
    "processing": "قيد المعالجة",
    "preparing": "قيد التحضير",
    "order_ready": "الطلب جاهز",
    "delivered": "تم التسليم",
    "today": "اليوم",
    "yesterday": "أمس",
    "this_week": "هذا الأسبوع",
    "this_month": "هذا الشهر",
    "sales_report": "تقرير المبيعات",
    "inventory_report": "تقرير المخزون",
    "profit_report": "تقرير الأرباح",
    "daily_sales": "المبيعات اليومية",
    "monthly_sales": "المبيعات الشهرية",
    "yearly_sales": "المبيعات السنوية",
    "top_selling_products": "المنتجات الأكثر مبيعاً",
    "low_stock_products": "المنتجات منخفضة المخزون",
    "out_of_stock": "نفد من المخزون",
    "in_stock": "متوفر في المخزون",
    "stock_level": "مستوى المخزون",
    "reorder_level": "مستوى إعادة الطلب",
    "supplier": "المورد",
    "cost_price": "سعر التكلفة",
    "selling_price": "سعر البيع",
    "profit_margin": "هامش الربح",
    "barcode": "الرمز الشريطي",
    "sku": "رمز المنتج",
    "image": "الصورة",
    "upload_image": "رفع صورة",
    "remove_image": "إزالة الصورة",
    "product_image": "صورة المنتج",
    "category_image": "صورة التصنيف",
    "business_logo": "شعار المتجر",
    "receipt_logo": "شعار الفاتورة",
    "theme": "المظهر",
    "light_theme": "المظهر الفاتح",
    "dark_theme": "المظهر الداكن",
    "system_theme": "مظهر النظام",
    "notifications": "الإشعارات",
    "sound_notifications": "الإشعارات الصوتية",
    "email_notifications": "إشعارات البريد الإلكتروني",
    "sms_notifications": "إشعارات الرسائل النصية",
    "backup": "النسخ الاحتياطي",
    "restore": "الاستعادة",
    "backup_data": "نسخ احتياطي للبيانات",
    "restore_data": "استعادة البيانات",
    "data_management": "إدارة البيانات",
    "clear_data": "مسح البيانات",
    "reset_system": "إعادة تعيين النظام",
    "system_info": "معلومات النظام",
    "version": "الإصدار",
    "build_date": "تاريخ الإنشاء",
    "support": "الدعم الفني",
    "help": "المساعدة",
    "about": "حول",
    "contact": "اتصل بنا",
    "feedback": "الملاحظات",
    "report_bug": "الإبلاغ عن خطأ",
    "feature_request": "طلب ميزة جديدة",
    "documentation": "التوثيق",
    "tutorials": "البرامج التعليمية",
    "faq": "الأسئلة الشائعة",
    "keyboard_shortcuts": "اختصارات لوحة المفاتيح",
    "shortcuts": "الاختصارات",
    "hotkeys": "المفاتيح السريعة",
    "tips": "النصائح",
    "getting_started": "البدء",
    "quick_start": "البدء السريع",
    "advanced_settings": "الإعدادات المتقدمة",
    "basic_settings": "الإعدادات الأساسية",
    "custom_settings": "الإعدادات المخصصة",
    "default_settings": "الإعدادات الافتراضية",
    "import_settings": "استيراد الإعدادات",
    "export_settings": "تصدير الإعدادات",
    "sync_settings": "مزامنة الإعدادات",
    "cloud_sync": "المزامنة السحابية",
    "local_storage": "التخزين المحلي",
    "cloud_storage": "التخزين السحابي",
    "security": "الأمان",
    "privacy": "الخصوصية",
    "data_protection": "حماية البيانات",
    "encryption": "التشفير",
    "access_control": "التحكم في الوصول",
    "user_roles": "أدوار المستخدمين",
    "admin_role": "دور المدير",
    "cashier_role": "دور الكاشير",
    "kitchen_role": "دور المطبخ",
    "manager_role": "دور المدير العام",
    "staff_role": "دور الموظف",
    "guest_role": "دور الضيف",
    "full_access": "وصول كامل",
    "limited_access": "وصول محدود",
    "read_only": "قراءة فقط",
    "read_write": "قراءة وكتابة",
    "no_access": "لا يوجد وصول",
    "session_timeout": "انتهاء مهلة الجلسة",
    "auto_logout": "تسجيل خروج تلقائي",
    "login_attempts": "محاولات تسجيل الدخول",
    "password_policy": "سياسة كلمة المرور",
    "strong_password": "كلمة مرور قوية",
    "weak_password": "كلمة مرور ضعيفة",
    "password_strength": "قوة كلمة المرور",
    "confirm_password": "تأكيد كلمة المرور",
    "current_password": "كلمة المرور الحالية",
    "new_password": "كلمة المرور الجديدة",
    "change_password": "تغيير كلمة المرور",
    "forgot_password": "نسيت كلمة المرور",
    "reset_password": "إعادة تعيين كلمة المرور",
    "remember_me": "تذكرني",
    "stay_signed_in": "البقاء متصلاً",
    "sign_out": "تسجيل الخروج",
    "sign_up": "التسجيل",
    "create_account": "إنشاء حساب",
    "account_created": "تم إنشاء الحساب",
    "account_updated": "تم تحديث الحساب",
    "account_deleted": "تم حذف الحساب",
    "profile": "الملف الشخصي",
    "edit_profile": "تعديل الملف الشخصي",
    "profile_picture": "صورة الملف الشخصي",
    "personal_info": "المعلومات الشخصية",
    "contact_info": "معلومات الاتصال",
    "first_name": "الاسم الأول",
    "last_name": "الاسم الأخير",
    "full_name": "الاسم الكامل",
    "email": "البريد الإلكتروني",
    "phone": "رقم الهاتف",
    "mobile": "رقم الجوال",
    "address": "العنوان",
    "city": "المدينة",
    "state": "الولاية",
    "country": "البلد",
    "postal_code": "الرمز البريدي",
    "zip_code": "رمز المنطقة",
    "date_of_birth": "تاريخ الميلاد",
    "age": "العمر",
    "gender": "الجنس",
    "male": "ذكر",
    "female": "أنثى",
    "other": "أخرى",
    "language": "اللغة",
    "timezone": "المنطقة الزمنية",
    "date_format": "تنسيق التاريخ",
    "time_format": "تنسيق الوقت",
    "number_format": "تنسيق الأرقام",
    "currency_format": "تنسيق العملة",
    "decimal_places": "الأماكن العشرية",
    "thousands_separator": "فاصل الآلاف",
    "decimal_separator": "الفاصل العشري",
    "round_amounts": "تقريب المبالغ",
    "show_zero_amounts": "إظهار المبالغ الصفرية",
    "hide_zero_amounts": "إخفاء المبالغ الصفرية",
    "tax_inclusive": "شامل الضريبة",
    "tax_exclusive": "غير شامل الضريبة",
    "before_tax": "قبل الضريبة",
    "after_tax": "بعد الضريبة",
    "including_tax": "بما في ذلك الضريبة",
    "excluding_tax": "باستثناء الضريبة",
    "vat": "ضريبة القيمة المضافة",
    "sales_tax": "ضريبة المبيعات",
    "service_charge": "رسوم الخدمة",
    "delivery_charge": "رسوم التوصيل",
    "packaging_charge": "رسوم التغليف",
    "extra_charge": "رسوم إضافية",
    "additional_fees": "رسوم إضافية",
    "surcharge": "رسوم إضافية",
    "fee": "رسم",
    "commission": "عمولة",
    "tip": "إكرامية",
    "gratuity": "إكرامية",
    "service_tip": "إكرامية الخدمة",
    "auto_gratuity": "إكرامية تلقائية",
    "suggested_tip": "إكرامية مقترحة",
    "custom_tip": "إكرامية مخصصة",
    "no_tip": "بدون إكرامية",
    "round_up": "تقريب لأعلى",
    "round_down": "تقريب لأسفل",
    "exact_amount": "المبلغ الدقيق",

    // Additional comprehensive translations
    "welcome_to_pos": "مرحباً بك في نظام نقاط البيع",
    "pos_system": "نظام نقاط البيع",
    "dashboard_overview": "نظرة عامة على لوحة التحكم",
    "todays_sales": "مبيعات اليوم",
    "total_orders": "إجمالي الطلبات",
    "active_orders": "الطلبات النشطة",
    "total_revenue": "إجمالي الإيرادات",
    "best_selling_item": "أكثر الأصناف مبيعاً",
    "recent_orders": "الطلبات الأخيرة",
    "quick_actions": "الإجراءات السريعة",
    "view_all_orders": "عرض جميع الطلبات",
    "manage_inventory": "إدارة المخزون",
    "generate_report": "إنشاء تقرير",
    "system_settings": "إعدادات النظام",
    "user_profile": "الملف الشخصي للمستخدم",
    "change_user": "تغيير المستخدم",
    "system_status": "حالة النظام",
    "online_status": "الحالة متصل",
    "offline_status": "الحالة غير متصل",
    "connection_status": "حالة الاتصال",
    "last_sync": "آخر مزامنة",
    "sync_now": "مزامنة الآن",
    "auto_sync": "مزامنة تلقائية",
    "manual_sync": "مزامنة يدوية",
    "sync_settings": "إعدادات المزامنة",
    "data_sync": "مزامنة البيانات",
    "backup_frequency": "تكرار النسخ الاحتياطي",
    "auto_backup": "نسخ احتياطي تلقائي",
    "manual_backup": "نسخ احتياطي يدوي",
    "restore_backup": "استعادة النسخة الاحتياطية",
    "backup_location": "موقع النسخ الاحتياطي",
    "cloud_backup": "نسخ احتياطي سحابي",
    "local_backup": "نسخ احتياطي محلي",
    "backup_schedule": "جدولة النسخ الاحتياطي",
    "daily_backup": "نسخ احتياطي يومي",
    "weekly_backup": "نسخ احتياطي أسبوعي",
    "monthly_backup": "نسخ احتياطي شهري",
    "backup_retention": "الاحتفاظ بالنسخ الاحتياطية",
    "retain_backups": "الاحتفاظ بالنسخ",
    "delete_old_backups": "حذف النسخ القديمة",
    "backup_size": "حجم النسخة الاحتياطية",
    "backup_date": "تاريخ النسخة الاحتياطية",
    "backup_time": "وقت النسخة الاحتياطية",
    "backup_status": "حالة النسخة الاحتياطية",
    "backup_progress": "تقدم النسخ الاحتياطي",
    "backup_complete": "اكتمل النسخ الاحتياطي",
    "backup_failed": "فشل النسخ الاحتياطي",
    "backup_in_progress": "النسخ الاحتياطي قيد التقدم",
    "restore_complete": "اكتملت الاستعادة",
    "restore_failed": "فشلت الاستعادة",
    "restore_in_progress": "الاستعادة قيد التقدم",
    "select_backup": "اختيار النسخة الاحتياطية",
    "backup_file": "ملف النسخة الاحتياطية",
    "upload_backup": "رفع النسخة الاحتياطية",
    "download_backup": "تحميل النسخة الاحتياطية",
    "verify_backup": "التحقق من النسخة الاحتياطية",
    "backup_verified": "تم التحقق من النسخة الاحتياطية",
    "backup_corrupted": "النسخة الاحتياطية تالفة",
    "page_not_found": "الصفحة غير موجودة",
    "go_back_home": "العودة للصفحة الرئيسية",
    "go_to_dashboard": "الذهاب للوحة التحكم",
    "error_404": "خطأ 404",
    "page_does_not_exist": "هذه الصفحة غير موجودة",
    "check_url": "تحقق من الرابط",
    "contact_support": "اتصل بالدعم الفني",
    "error_occurred": "حدث خطأ",
    "try_again": "حاول مرة أخرى",
    "reload_page": "إعادة تحميل الصفحة",
    "go_back": "الرجوع",
    "home_page": "الصفحة الرئيسية",
    "main_page": "الصفحة الرئيسية",
    "start_page": "صفحة البداية",
    "default_page": "الصفحة الافتراضية",
    "landing_page": "صفحة الهبوط",
    "introduction": "مقدمة",
    "welcome_message": "رسالة ترحيب",
    "getting_started_guide": "دليل البدء",
    "user_guide": "دليل المستخدم",
    "how_to_use": "كيفية الاستخدام",
    "step_by_step": "خطوة بخطوة",
    "instructions": "التعليمات",
    "manual": "الدليل",
    "handbook": "كتيب الإرشادات",
    "reference": "المرجع",
    "guide": "الدليل",
    "tutorial": "البرنامج التعليمي",
    "lesson": "الدرس",
    "course": "الدورة",
    "training": "التدريب",
    "learning": "التعلم",
    "education": "التعليم",
    "knowledge": "المعرفة",
    "skill": "المهارة",
    "expertise": "الخبرة",
    "experience": "التجربة",
    "practice": "الممارسة",
    "exercise": "التمرين",
    "example": "المثال",
    "demo": "العرض التوضيحي",
    "sample": "العينة",
    "template": "القالب",
    "format": "التنسيق",
    "layout": "التخطيط",
    "design": "التصميم",
    "style": "الأسلوب",
    "appearance": "المظهر",
    "look": "الشكل",
    "feel": "الملمس",
    "interface": "الواجهة",
    "user_interface": "واجهة المستخدم",
    "ui": "واجهة المستخدم",
    "ux": "تجربة المستخدم",
    "user_experience": "تجربة المستخدم",
    "usability": "سهولة الاستخدام",
    "accessibility": "إمكانية الوصول",
    "navigation": "التنقل",
    "menu": "القائمة",
    "toolbar": "شريط الأدوات",
    "sidebar": "الشريط الجانبي",
    "header": "الرأس",
    "footer": "التذييل",
    "content": "المحتوى",
    "main_content": "المحتوى الرئيسي",
    "primary_content": "المحتوى الأساسي",
    "secondary_content": "المحتوى الثانوي",
    "additional_content": "المحتوى الإضافي",
    "extra_content": "المحتوى الإضافي",
    "related_content": "المحتوى ذو الصلة",
    "similar_content": "المحتوى المشابه",
    "recommended_content": "المحتوى المُوصى به",
    "featured_content": "المحتوى المميز",
    "popular_content": "المحتوى الشائع",
    "trending_content": "المحتوى الرائج",
    "latest_content": "أحدث المحتوى",
    "recent_content": "المحتوى الحديث",
    "new_content": "المحتوى الجديد",
    "updated_content": "المحتوى المحدث",
    "fresh_content": "المحتوى الطازج",
    "current_content": "المحتوى الحالي",
    "live_content": "المحتوى المباشر",
    "real_time_content": "المحتوى في الوقت الفعلي",
    "dynamic_content": "المحتوى الديناميكي",
    "static_content": "المحتوى الثابت",
    "interactive_content": "المحتوى التفاعلي",
    "multimedia_content": "المحتوى متعدد الوسائط",
    "text_content": "المحتوى النصي",
    "image_content": "محتوى الصور",
    "video_content": "محتوى الفيديو",
    "audio_content": "المحتوى الصوتي",
    "media_content": "المحتوى الإعلامي",
    "digital_content": "المحتوى الرقمي",
    "online_content": "المحتوى الإلكتروني",
    "web_content": "محتوى الويب",
    "mobile_content": "المحتوى المحمول",
    "desktop_content": "محتوى سطح المكتب",
    "tablet_content": "محتوى الجهاز اللوحي",
    "responsive_content": "المحتوى المتجاوب",
    "adaptive_content": "المحتوى التكيفي",
    "flexible_content": "المحتوى المرن",
    "scalable_content": "المحتوى القابل للتوسع",
    "customizable_content": "المحتوى القابل للتخصيص",
    "personalized_content": "المحتوى الشخصي",
    "tailored_content": "المحتوى المخصص",
    "relevant_content": "المحتوى ذو الصلة",
    "targeted_content": "المحتوى المستهدف",
    "specific_content": "المحتوى المحدد",
    "general_content": "المحتوى العام",
    "broad_content": "المحتوى الواسع",
    "detailed_content": "المحتوى التفصيلي",
    "comprehensive_content": "المحتوى الشامل",
    "complete_content": "المحتوى الكامل",
    "full_content": "المحتوى الكامل",
    "partial_content": "المحتوى الجزئي",
    "limited_content": "المحتوى المحدود",
    "restricted_content": "المحتوى المقيد",
    "public_content": "المحتوى العام",
    "private_content": "المحتوى الخاص",
    "confidential_content": "المحتوى السري",
    "sensitive_content": "المحتوى الحساس",
    "secure_content": "المحتوى الآمن",
    "protected_content": "المحتوى المحمي",
    "encrypted_content": "المحتوى المشفر",
    "locked_content": "المحتوى المقفل",
    "unlocked_content": "المحتوى المفتوح",
    "open_content": "المحتوى المفتوح",
    "closed_content": "المحتوى المغلق",
    "available_content": "المحتوى المتاح",
    "unavailable_content": "المحتوى غير المتاح",
    "accessible_content": "المحتوى القابل للوصول",
    "inaccessible_content": "المحتوى غير القابل للوصول",
    "visible_content": "المحتوى المرئي",
    "hidden_content": "المحتوى المخفي",
    "displayed_content": "المحتوى المعروض",
    "concealed_content": "المحتوى المستور",
    "revealed_content": "المحتوى المكشوف",
    "exposed_content": "المحتوى المكشوف",
    "covered_content": "المحتوى المغطى",
    "uncovered_content": "المحتوى المكشوف",

    // Order Queue translations
    "order_queue_list": "قائمة انتظار الطلبات",
    "waiting_time_minutes": "وقت الانتظار (دقائق)",
    "not_specified": "غير محدد",
    "customer_queue_screen": "شاشة انتظار العملاء",
    "no_orders_in_queue": "لا توجد طلبات في قائمة الانتظار",
    "estimated_time": "الوقت المقدر",
    "elapsed_time": "الوقت المنقضي",
    "remaining_time": "الوقت المتبقي"
  },
  en: {
    // General
    "all_products": "All Products",
    "no_products_in_category": "No products in this category",
    "no_categories_available": "No categories available",
    "settings": "Settings",
    "save_settings": "Save Settings",
    "general": "General",
    "printing": "Printing",
    "business": "Business",
    "search_products": "Search products...",

    // Settings
    "general_settings": "General Settings",
    "auto_print_receipt": "Auto Print Receipt",
    "auto_print_receipt_desc": "Automatically print receipt when order is completed",
    "auto_kitchen_print": "Auto Kitchen Print",
    "auto_kitchen_print_desc": "Automatically send order to kitchen printer",
    "show_price_kitchen": "Show Prices on Kitchen Display",
    "show_price_kitchen_desc": "Display product prices on kitchen screen",
    "app_language": "Application Language",
    "app_language_desc": "Choose the user interface language",
    "currency_symbol": "Currency Symbol",
    "arabic": "العربية",
    "english": "English",
    "french": "Français",
    "choose_language": "Choose Language",

    // Printing settings
    "printing_settings": "Printing Settings",
    "receipt_printer": "Receipt Printer",
    "kitchen_printer": "Kitchen Printer",
    "choose_printer": "Choose a printer",
    "default_printer": "Default Printer",
    "thermal_printer": "Thermal Printer",
    "receipt_width": "Receipt Width (mm)",
    "show_logo": "Show Logo on Receipt",

    // Business settings
    "business_info": "Business Information",
    "business_name": "Business Name",
    "business_address": "Business Address",
    "business_phone": "Phone Number",
    "tax_rate": "Tax Rate (%)",
    "receipt_footer": "Receipt Footer Text",

    // Error messages
    "no_permission": "You don't have permission to edit settings",
    "settings_saved": "Settings saved successfully",
    "settings_error": "Error saving settings",
    "unauthorized": "Unauthorized",
    "no_access": "You don't have access to system settings",

    // Navigation and menu items
    "dashboard": "Dashboard",
    "cashier": "Cashier",
    "kitchen": "Kitchen",
    "admin": "Admin",
    "reports": "Reports",
    "products": "Products",
    "queue": "Queue",
    "logout": "Logout",

    // Login page
    "login": "Login",
    "username": "Username",
    "password": "Password",
    "show_password": "Show password",
    "hide_password": "Hide password",
    "sign_in": "Sign In",
    "invalid_credentials": "Invalid credentials",

    // Order management
    "new_order": "New Order",
    "current_order": "Current Order",
    "add_to_order": "Add to Order",
    "remove_from_order": "Remove from Order",
    "complete_order": "Complete Order",
    "cancel_order": "Cancel Order",
    "order_total": "Order Total",
    "subtotal": "Subtotal",
    "tax": "Tax",
    "discount": "Discount",
    "total": "Total",

    // Payment
    "payment": "Payment",
    "cash": "Cash",
    "card": "Card",
    "amount_paid": "Amount Paid",
    "change": "Change",

    // Product management
    "add_product": "Add Product",
    "edit_product": "Edit Product",
    "delete_product": "Delete Product",
    "product_name": "Product Name",
    "product_price": "Product Price",
    "product_category": "Product Category",
    "available": "Available",
    "unavailable": "Unavailable",

    // Categories
    "categories": "Categories",
    "add_category": "Add Category",
    "category_name": "Category Name",
    "edit_category": "Edit Category",
    "delete_category": "Delete Category",

    // Actions
    "add": "Add",
    "edit": "Edit",
    "delete": "Delete",
    "save": "Save",
    "cancel": "Cancel",
    "confirm": "Confirm",
    "close": "Close",
    "back": "Back",
    "next": "Next",
    "previous": "Previous",
    "submit": "Submit",
    "reset": "Reset",
    "clear": "Clear",
    "refresh": "Refresh",
    "search": "Search",
    "filter": "Filter",
    "sort": "Sort",
    "view": "View",
    "print": "Print",
    "download": "Download",
    "upload": "Upload",
    "import": "Import",
    "export": "Export",

    // Status
    "active": "Active",
    "inactive": "Inactive",
    "enabled": "Enabled",
    "disabled": "Disabled",
    "online": "Online",
    "offline": "Offline",
    "loading": "Loading...",
    "saving": "Saving...",
    "success": "Success",
    "error": "Error",
    "warning": "Warning",
    "info": "Information",

    // Common phrases
    "welcome": "Welcome",
    "goodbye": "Goodbye",
    "hello": "Hello",
    "thank_you": "Thank you",
    "please": "Please",
    "yes": "Yes",
    "no": "No",
    "ok": "OK",
    "maybe": "Maybe",
    "sure": "Sure",
    "definitely": "Definitely",
    "probably": "Probably",
    "possibly": "Possibly",

    // Missing translations
    "no_items_in_order": "No items in order",
    "order_summary": "Order Summary",
    "proceed_to_payment": "Proceed to Payment",
    "users": "Users",
    "user_management": "User Management",
    "add_user": "Add User",
    "edit_user": "Edit User",
    "delete_user": "Delete User",
    "role": "Role",
    "permissions": "Permissions",
    "status": "Status",
    "last_login": "Last Login",
    "created_date": "Created Date",
    "user_details": "User Details",
    "select_role": "Select Role",
    "password_confirm": "Confirm Password",
    "passwords_not_match": "Passwords do not match",
    "user_created": "User created successfully",
    "user_updated": "User updated successfully",
    "user_deleted": "User deleted successfully",
    "confirm_delete_user": "Are you sure you want to delete this user?",
    "manage_orders_and_status": "Manage orders and preparation status",
    "pending_orders": "Pending Orders",
    "in_progress": "In Progress",
    "ready": "Ready",
    "completed": "Completed",
    "cancelled": "Cancelled",
    "order_number": "Order Number",
    "order_time": "Order Time",
    "customer": "Customer",
    "items_count": "Items Count",
    "mark_as_ready": "Mark as Ready",
    "mark_as_completed": "Mark as Completed",
    "view_details": "View Details",

    // Additional missing translations
    "grand_total": "Grand Total",
    "item": "Item",
    "items": "Items",
    "quantity": "Quantity",
    "price": "Price",
    "amount": "Amount",
    "description": "Description",
    "note": "Note",
    "notes": "Notes",
    "customer_name": "Customer Name",
    "table_number": "Table Number",
    "order_type": "Order Type",
    "dine_in": "Dine In",
    "takeaway": "Takeaway",
    "delivery": "Delivery",
    "apply_discount": "Apply Discount",
    "discount_percentage": "Discount Percentage",
    "discount_amount": "Discount Amount",
    "apply": "Apply",
    "remove_discount": "Remove Discount",
    "payment_method": "Payment Method",
    "cash_payment": "Cash Payment",
    "card_payment": "Card Payment",
    "split_payment": "Split Payment",
    "received_amount": "Received Amount",
    "change_amount": "Change Amount",
    "print_receipt": "Print Receipt",
    "send_to_kitchen": "Send to Kitchen",
    "order_placed": "Order Placed",
    "processing": "Processing",
    "preparing": "Preparing",
    "order_ready": "Order Ready",
    "delivered": "Delivered",
    "today": "Today",
    "yesterday": "Yesterday",
    "this_week": "This Week",
    "this_month": "This Month",
    "sales_report": "Sales Report",
    "inventory_report": "Inventory Report",
    "profit_report": "Profit Report",
    "daily_sales": "Daily Sales",
    "monthly_sales": "Monthly Sales",
    "yearly_sales": "Yearly Sales",
    "top_selling_products": "Top Selling Products",
    "low_stock_products": "Low Stock Products",
    "out_of_stock": "Out of Stock",
    "in_stock": "In Stock",
    "stock_level": "Stock Level",
    "reorder_level": "Reorder Level",
    "supplier": "Supplier",
    "cost_price": "Cost Price",
    "selling_price": "Selling Price",
    "profit_margin": "Profit Margin",
    "barcode": "Barcode",
    "sku": "SKU",
    "image": "Image",
    "upload_image": "Upload Image",
    "remove_image": "Remove Image",
    "product_image": "Product Image",
    "category_image": "Category Image",
    "business_logo": "Business Logo",
    "receipt_logo": "Receipt Logo",
    "theme": "Theme",
    "light_theme": "Light Theme",
    "dark_theme": "Dark Theme",
    "system_theme": "System Theme",
    "notifications": "Notifications",
    "sound_notifications": "Sound Notifications",
    "email_notifications": "Email Notifications",
    "sms_notifications": "SMS Notifications",
    "backup": "Backup",
    "restore": "Restore",
    "backup_data": "Backup Data",
    "restore_data": "Restore Data",
    "data_management": "Data Management",
    "clear_data": "Clear Data",
    "reset_system": "Reset System",
    "system_info": "System Information",
    "version": "Version",
    "build_date": "Build Date",
    "support": "Support",
    "help": "Help",
    "about": "About",
    "contact": "Contact",
    "feedback": "Feedback",
    "report_bug": "Report Bug",
    "feature_request": "Feature Request",
    "documentation": "Documentation",
    "tutorials": "Tutorials",
    "faq": "FAQ",
    "keyboard_shortcuts": "Keyboard Shortcuts",
    "shortcuts": "Shortcuts",
    "hotkeys": "Hotkeys",
    "tips": "Tips",
    "getting_started": "Getting Started",
    "quick_start": "Quick Start",
    "advanced_settings": "Advanced Settings",
    "basic_settings": "Basic Settings",
    "custom_settings": "Custom Settings",
    "default_settings": "Default Settings",
    "import_settings": "Import Settings",
    "export_settings": "Export Settings",
    "sync_settings": "Sync Settings",
    "cloud_sync": "Cloud Sync",
    "local_storage": "Local Storage",
    "cloud_storage": "Cloud Storage",
    "security": "Security",
    "privacy": "Privacy",
    "data_protection": "Data Protection",
    "encryption": "Encryption",
    "access_control": "Access Control",
    "user_roles": "User Roles",
    "admin_role": "Admin Role",
    "cashier_role": "Cashier Role",
    "kitchen_role": "Kitchen Role",
    "manager_role": "Manager Role",
    "staff_role": "Staff Role",
    "guest_role": "Guest Role",
    "full_access": "Full Access",
    "limited_access": "Limited Access",
    "read_only": "Read Only",
    "read_write": "Read Write",
    "no_access": "No Access",
    "session_timeout": "Session Timeout",
    "auto_logout": "Auto Logout",
    "login_attempts": "Login Attempts",
    "password_policy": "Password Policy",
    "strong_password": "Strong Password",
    "weak_password": "Weak Password",
    "password_strength": "Password Strength",
    "confirm_password": "Confirm Password",
    "current_password": "Current Password",
    "new_password": "New Password",
    "change_password": "Change Password",
    "forgot_password": "Forgot Password",
    "reset_password": "Reset Password",
    "remember_me": "Remember Me",
    "stay_signed_in": "Stay Signed In",
    "sign_out": "Sign Out",
    "sign_up": "Sign Up",
    "create_account": "Create Account",
    "account_created": "Account Created",
    "account_updated": "Account Updated",
    "account_deleted": "Account Deleted",
    "profile": "Profile",
    "edit_profile": "Edit Profile",
    "profile_picture": "Profile Picture",
    "personal_info": "Personal Information",
    "contact_info": "Contact Information",
    "first_name": "First Name",
    "last_name": "Last Name",
    "full_name": "Full Name",
    "email": "Email",
    "phone": "Phone",
    "mobile": "Mobile",
    "address": "Address",
    "city": "City",
    "state": "State",
    "country": "Country",
    "postal_code": "Postal Code",
    "zip_code": "ZIP Code",
    "date_of_birth": "Date of Birth",
    "age": "Age",
    "gender": "Gender",
    "male": "Male",
    "female": "Female",
    "other": "Other",
    "language": "Language",
    "timezone": "Timezone",
    "date_format": "Date Format",
    "time_format": "Time Format",
    "number_format": "Number Format",
    "currency_format": "Currency Format",
    "decimal_places": "Decimal Places",
    "thousands_separator": "Thousands Separator",
    "decimal_separator": "Decimal Separator",
    "round_amounts": "Round Amounts",
    "show_zero_amounts": "Show Zero Amounts",
    "hide_zero_amounts": "Hide Zero Amounts",
    "tax_inclusive": "Tax Inclusive",
    "tax_exclusive": "Tax Exclusive",
    "before_tax": "Before Tax",
    "after_tax": "After Tax",
    "including_tax": "Including Tax",
    "excluding_tax": "Excluding Tax",
    "vat": "VAT",
    "sales_tax": "Sales Tax",
    "service_charge": "Service Charge",
    "delivery_charge": "Delivery Charge",
    "packaging_charge": "Packaging Charge",
    "extra_charge": "Extra Charge",
    "additional_fees": "Additional Fees",
    "surcharge": "Surcharge",
    "fee": "Fee",
    "commission": "Commission",
    "tip": "Tip",
    "gratuity": "Gratuity",
    "service_tip": "Service Tip",
    "auto_gratuity": "Auto Gratuity",
    "suggested_tip": "Suggested Tip",
    "custom_tip": "Custom Tip",
    "no_tip": "No Tip",
    "round_up": "Round Up",
    "round_down": "Round Down",
    "exact_amount": "Exact Amount",

    // Additional comprehensive translations
    "welcome_to_pos": "Welcome to POS System",
    "pos_system": "POS System",
    "dashboard_overview": "Dashboard Overview",
    "todays_sales": "Today's Sales",
    "total_orders": "Total Orders",
    "active_orders": "Active Orders",
    "total_revenue": "Total Revenue",
    "best_selling_item": "Best Selling Item",
    "recent_orders": "Recent Orders",
    "quick_actions": "Quick Actions",
    "view_all_orders": "View All Orders",
    "manage_inventory": "Manage Inventory",
    "generate_report": "Generate Report",
    "system_settings": "System Settings",
    "user_profile": "User Profile",
    "change_user": "Change User",
    "system_status": "System Status",
    "online_status": "Online",
    "offline_status": "Offline",
    "connection_status": "Connection Status",
    "last_sync": "Last Sync",
    "sync_now": "Sync Now",
    "auto_sync": "Auto Sync",
    "manual_sync": "Manual Sync",
    "sync_settings": "Sync Settings",
    "data_sync": "Data Sync",
    "backup_frequency": "Backup Frequency",
    "auto_backup": "Auto Backup",
    "manual_backup": "Manual Backup",
    "restore_backup": "Restore Backup",
    "backup_location": "Backup Location",
    "cloud_backup": "Cloud Backup",
    "local_backup": "Local Backup",
    "backup_schedule": "Backup Schedule",
    "daily_backup": "Daily Backup",
    "weekly_backup": "Weekly Backup",
    "monthly_backup": "Monthly Backup",
    "backup_retention": "Backup Retention",
    "retain_backups": "Retain Backups",
    "delete_old_backups": "Delete Old Backups",
    "backup_size": "Backup Size",
    "backup_date": "Backup Date",
    "backup_time": "Backup Time",
    "backup_status": "Backup Status",
    "backup_progress": "Backup Progress",
    "backup_complete": "Backup Complete",
    "backup_failed": "Backup Failed",
    "backup_in_progress": "Backup In Progress",
    "restore_complete": "Restore Complete",
    "restore_failed": "Restore Failed",
    "restore_in_progress": "Restore In Progress",
    "select_backup": "Select Backup",
    "backup_file": "Backup File",
    "upload_backup": "Upload Backup",
    "download_backup": "Download Backup",
    "verify_backup": "Verify Backup",
    "backup_verified": "Backup Verified",
    "backup_corrupted": "Backup Corrupted",
    "page_not_found": "Page Not Found",
    "go_back_home": "Go Back Home",
    "go_to_dashboard": "Go to Dashboard",
    "error_404": "Error 404",
    "page_does_not_exist": "This page does not exist",
    "check_url": "Check URL",
    "contact_support": "Contact Support",
    "error_occurred": "An error occurred",
    "try_again": "Try Again",
    "reload_page": "Reload Page",
    "go_back": "Go Back",
    "home_page": "Home Page",
    "main_page": "Main Page",
    "start_page": "Start Page",
    "default_page": "Default Page",
    "landing_page": "Landing Page",
    "introduction": "Introduction",
    "welcome_message": "Welcome Message",
    "getting_started_guide": "Getting Started Guide",
    "user_guide": "User Guide",
    "how_to_use": "How to Use",
    "step_by_step": "Step by Step",
    "instructions": "Instructions",
    "manual": "Manual",
    "handbook": "Handbook",
    "reference": "Reference",
    "guide": "Guide",
    "tutorial": "Tutorial",
    "lesson": "Lesson",
    "course": "Course",
    "training": "Training",
    "learning": "Learning",
    "education": "Education",
    "knowledge": "Knowledge",
    "skill": "Skill",
    "expertise": "Expertise",
    "experience": "Experience",
    "practice": "Practice",
    "exercise": "Exercise",
    "example": "Example",
    "demo": "Demo",
    "sample": "Sample",
    "template": "Template",
    "format": "Format",
    "layout": "Layout",
    "design": "Design",
    "style": "Style",
    "appearance": "Appearance",
    "look": "Look",
    "feel": "Feel",
    "interface": "Interface",
    "user_interface": "User Interface",
    "ui": "UI",
    "ux": "UX",
    "user_experience": "User Experience",
    "usability": "Usability",
    "accessibility": "Accessibility",
    "navigation": "Navigation",
    "menu": "Menu",
    "toolbar": "Toolbar",
    "sidebar": "Sidebar",
    "header": "Header",
    "footer": "Footer",
    "content": "Content",
    "main_content": "Main Content",
    "primary_content": "Primary Content",
    "secondary_content": "Secondary Content",
    "additional_content": "Additional Content",
    "extra_content": "Extra Content",
    "related_content": "Related Content",
    "similar_content": "Similar Content",
    "recommended_content": "Recommended Content",
    "featured_content": "Featured Content",
    "popular_content": "Popular Content",
    "trending_content": "Trending Content",
    "latest_content": "Latest Content",
    "recent_content": "Recent Content",
    "new_content": "New Content",
    "updated_content": "Updated Content",
    "fresh_content": "Fresh Content",
    "current_content": "Current Content",
    "live_content": "Live Content",
    "real_time_content": "Real-time Content",
    "dynamic_content": "Dynamic Content",
    "static_content": "Static Content",
    "interactive_content": "Interactive Content",
    "multimedia_content": "Multimedia Content",
    "text_content": "Text Content",
    "image_content": "Image Content",
    "video_content": "Video Content",
    "audio_content": "Audio Content",
    "media_content": "Media Content",
    "digital_content": "Digital Content",
    "online_content": "Online Content",
    "web_content": "Web Content",
    "mobile_content": "Mobile Content",
    "desktop_content": "Desktop Content",
    "tablet_content": "Tablet Content",
    "responsive_content": "Responsive Content",
    "adaptive_content": "Adaptive Content",
    "flexible_content": "Flexible Content",
    "scalable_content": "Scalable Content",
    "customizable_content": "Customizable Content",
    "personalized_content": "Personalized Content",
    "tailored_content": "Tailored Content",
    "relevant_content": "Relevant Content",
    "targeted_content": "Targeted Content",
    "specific_content": "Specific Content",
    "general_content": "General Content",
    "broad_content": "Broad Content",
    "detailed_content": "Detailed Content",
    "comprehensive_content": "Comprehensive Content",
    "complete_content": "Complete Content",
    "full_content": "Full Content",
    "partial_content": "Partial Content",
    "limited_content": "Limited Content",
    "restricted_content": "Restricted Content",
    "public_content": "Public Content",
    "private_content": "Private Content",
    "confidential_content": "Confidential Content",
    "sensitive_content": "Sensitive Content",
    "secure_content": "Secure Content",
    "protected_content": "Protected Content",
    "encrypted_content": "Encrypted Content",
    "locked_content": "Locked Content",
    "unlocked_content": "Unlocked Content",
    "open_content": "Open Content",
    "closed_content": "Closed Content",
    "available_content": "Available Content",
    "unavailable_content": "Unavailable Content",
    "accessible_content": "Accessible Content",
    "inaccessible_content": "Inaccessible Content",
    "visible_content": "Visible Content",
    "hidden_content": "Hidden Content",
    "displayed_content": "Displayed Content",
    "concealed_content": "Concealed Content",
    "revealed_content": "Revealed Content",
    "exposed_content": "Exposed Content",
    "covered_content": "Covered Content",
    "uncovered_content": "Uncovered Content",

    // Order Queue translations
    "order_queue_list": "Order Queue List",
    "waiting_time_minutes": "Waiting Time (minutes)",
    "not_specified": "Not Specified",
    "customer_queue_screen": "Customer Queue Screen",
    "no_orders_in_queue": "No orders in queue",
    "estimated_time": "Estimated Time",
    "elapsed_time": "Elapsed Time",
    "remaining_time": "Remaining Time"
  },
  fr: {
    // General
    "all_products": "Tous les produits",
    "no_products_in_category": "Aucun produit dans cette catégorie",
    "no_categories_available": "Aucune catégorie disponible",
    "settings": "Paramètres",
    "save_settings": "Enregistrer les paramètres",
    "general": "Général",
    "printing": "Impression",
    "business": "Entreprise",
    "search_products": "Rechercher des produits...",

    // Settings
    "general_settings": "Paramètres généraux",
    "auto_print_receipt": "Impression automatique du reçu",
    "auto_print_receipt_desc": "Imprimer automatiquement le reçu à la fin de la commande",
    "auto_kitchen_print": "Impression automatique cuisine",
    "auto_kitchen_print_desc": "Envoyer automatiquement la commande à l'imprimante de cuisine",
    "show_price_kitchen": "Afficher les prix sur l'écran cuisine",
    "show_price_kitchen_desc": "Afficher les prix des produits sur l'écran de cuisine",
    "app_language": "Langue de l'application",
    "app_language_desc": "Choisir la langue de l'interface utilisateur",
    "currency_symbol": "Symbole de devise",
    "arabic": "العربية",
    "english": "English",
    "french": "Français",
    "choose_language": "Choisir la langue",

    // Printing settings
    "printing_settings": "Paramètres d'impression",
    "receipt_printer": "Imprimante de reçus",
    "kitchen_printer": "Imprimante de cuisine",
    "choose_printer": "Choisir une imprimante",
    "default_printer": "Imprimante par défaut",
    "thermal_printer": "Imprimante thermique",
    "receipt_width": "Largeur du reçu (mm)",
    "show_logo": "Afficher le logo sur le reçu",

    // Business settings
    "business_info": "Informations de l'entreprise",
    "business_name": "Nom de l'entreprise",
    "business_address": "Adresse de l'entreprise",
    "business_phone": "Numéro de téléphone",
    "tax_rate": "Taux de taxe (%)",
    "receipt_footer": "Texte de pied de reçu",

    // Error messages
    "no_permission": "Vous n'avez pas la permission de modifier les paramètres",
    "settings_saved": "Paramètres enregistrés avec succès",
    "settings_error": "Erreur lors de l'enregistrement des paramètres",
    "unauthorized": "Non autorisé",
    "no_access": "Vous n'avez pas accès aux paramètres du système",

    // Navigation and menu items
    "dashboard": "Tableau de bord",
    "cashier": "Caissier",
    "kitchen": "Cuisine",
    "admin": "Administration",
    "reports": "Rapports",
    "products": "Produits",
    "queue": "File d'attente",
    "logout": "Déconnexion",

    // Login page
    "login": "Connexion",
    "username": "Nom d'utilisateur",
    "password": "Mot de passe",
    "show_password": "Afficher le mot de passe",
    "hide_password": "Masquer le mot de passe",
    "sign_in": "Se connecter",
    "invalid_credentials": "Identifiants invalides",

    // Order management
    "new_order": "Nouvelle commande",
    "current_order": "Commande actuelle",
    "add_to_order": "Ajouter à la commande",
    "remove_from_order": "Retirer de la commande",
    "complete_order": "Terminer la commande",
    "cancel_order": "Annuler la commande",
    "order_total": "Total de la commande",
    "subtotal": "Sous-total",
    "tax": "Taxe",
    "discount": "Remise",
    "total": "Total",

    // Payment
    "payment": "Paiement",
    "cash": "Espèces",
    "card": "Carte",
    "amount_paid": "Montant payé",
    "change": "Monnaie",

    // Product management
    "add_product": "Ajouter un produit",
    "edit_product": "Modifier le produit",
    "delete_product": "Supprimer le produit",
    "product_name": "Nom du produit",
    "product_price": "Prix du produit",
    "product_category": "Catégorie du produit",
    "available": "Disponible",
    "unavailable": "Non disponible",

    // Categories
    "categories": "Catégories",
    "add_category": "Ajouter une catégorie",
    "category_name": "Nom de la catégorie",
    "edit_category": "Modifier la catégorie",
    "delete_category": "Supprimer la catégorie",

    // Actions
    "add": "Ajouter",
    "edit": "Modifier",
    "delete": "Supprimer",
    "save": "Enregistrer",
    "cancel": "Annuler",
    "confirm": "Confirmer",
    "close": "Fermer",
    "back": "Retour",
    "next": "Suivant",
    "previous": "Précédent",
    "submit": "Soumettre",
    "reset": "Réinitialiser",
    "clear": "Effacer",
    "refresh": "Actualiser",
    "search": "Rechercher",
    "filter": "Filtrer",
    "sort": "Trier",
    "view": "Voir",
    "print": "Imprimer",
    "download": "Télécharger",
    "upload": "Téléverser",
    "import": "Importer",
    "export": "Exporter",

    // Status
    "active": "Actif",
    "inactive": "Inactif",
    "enabled": "Activé",
    "disabled": "Désactivé",
    "online": "En ligne",
    "offline": "Hors ligne",
    "loading": "Chargement...",
    "saving": "Enregistrement...",
    "success": "Succès",
    "error": "Erreur",
    "warning": "Avertissement",
    "info": "Information",

    // Common phrases
    "welcome": "Bienvenue",
    "goodbye": "Au revoir",
    "hello": "Bonjour",
    "thank_you": "Merci",
    "please": "S'il vous plaît",
    "yes": "Oui",
    "no": "Non",
    "ok": "D'accord",
    "maybe": "Peut-être",
    "sure": "Sûr",
    "definitely": "Définitivement",
    "probably": "Probablement",
    "possibly": "Possiblement",

    // Missing translations
    "no_items_in_order": "Aucun article dans la commande",
    "order_summary": "Résumé de la commande",
    "proceed_to_payment": "Procéder au paiement",
    "users": "Utilisateurs",
    "user_management": "Gestion des utilisateurs",
    "add_user": "Ajouter un utilisateur",
    "edit_user": "Modifier l'utilisateur",
    "delete_user": "Supprimer l'utilisateur",
    "role": "Rôle",
    "permissions": "Permissions",
    "status": "Statut",
    "last_login": "Dernière connexion",
    "created_date": "Date de création",
    "user_details": "Détails de l'utilisateur",
    "select_role": "Sélectionner un rôle",
    "password_confirm": "Confirmer le mot de passe",
    "passwords_not_match": "Les mots de passe ne correspondent pas",
    "user_created": "Utilisateur créé avec succès",
    "user_updated": "Utilisateur mis à jour avec succès",
    "user_deleted": "Utilisateur supprimé avec succès",
    "confirm_delete_user": "Êtes-vous sûr de vouloir supprimer cet utilisateur?",
    "manage_orders_and_status": "Gérer les commandes et le statut de préparation",
    "pending_orders": "Commandes en attente",
    "in_progress": "En cours",
    "ready": "Prêt",
    "completed": "Terminé",
    "cancelled": "Annulé",
    "order_number": "Numéro de commande",
    "order_time": "Heure de commande",
    "customer": "Client",
    "items_count": "Nombre d'articles",
    "mark_as_ready": "Marquer comme prêt",
    "mark_as_completed": "Marquer comme terminé",
    "view_details": "Voir les détails",
    "grand_total": "Total général",
    "item": "Article",
    "items": "Articles",
    "quantity": "Quantité",
    "price": "Prix",
    "amount": "Montant",
    "description": "Description",
    "note": "Note",
    "notes": "Notes",
    "customer_name": "Nom du client",
    "table_number": "Numéro de table",
    "order_type": "Type de commande",
    "dine_in": "Sur place",
    "takeaway": "À emporter",
    "delivery": "Livraison",
    "apply_discount": "Appliquer une remise",
    "discount_percentage": "Pourcentage de remise",
    "discount_amount": "Montant de la remise",
    "apply": "Appliquer",
    "remove_discount": "Supprimer la remise",
    "payment_method": "Mode de paiement",
    "cash_payment": "Paiement en espèces",
    "card_payment": "Paiement par carte",
    "split_payment": "Paiement divisé",
    "received_amount": "Montant reçu",
    "change_amount": "Montant de la monnaie",
    "print_receipt": "Imprimer le reçu",
    "send_to_kitchen": "Envoyer en cuisine",
    "order_placed": "Commande passée",
    "processing": "En cours de traitement",
    "preparing": "En préparation",
    "order_ready": "Commande prête",
    "delivered": "Livré",
    "today": "Aujourd'hui",
    "yesterday": "Hier",
    "this_week": "Cette semaine",
    "this_month": "Ce mois",
    "this_year": "Cette année",
    "last_week": "La semaine dernière",
    "last_month": "Le mois dernier",
    "last_year": "L'année dernière",
    "total": "Total",
    "average": "Moyenne",
    "minimum": "Minimum",
    "maximum": "Maximum",
    "count": "Nombre",
    "sum": "Somme",
    "percentage": "Pourcentage",
    "ratio": "Ratio",
    "rate": "Taux",
    "frequency": "Fréquence",
    "duration": "Durée",
    "time": "Temps",
    "date": "Date",
    "timestamp": "Horodatage",
    "period": "Période",
    "range": "Plage",
    "from": "De",
    "to": "À",
    "until": "Jusqu'à",
    "since": "Depuis",
    "before": "Avant",
    "after": "Après",
    "during": "Pendant",
    "within": "Dans",
    "between": "Entre",
    "among": "Parmi",
    "inside": "À l'intérieur",
    "outside": "À l'extérieur",
    "above": "Au-dessus",
    "below": "En dessous",
    "over": "Plus de",
    "under": "Moins de",
    "equal": "Égal",
    "not_equal": "Pas égal",
    "greater": "Plus grand",
    "less": "Plus petit",
    "greater_equal": "Plus grand ou égal",
    "less_equal": "Plus petit ou égal",
    "cashier_screen": "Écran de caisse",
    "sales_screen": "Écran de vente",
    "pos_screen": "Écran de point de vente",
    "point_of_sale": "Point de vente",
    "cash_register": "Caisse enregistreuse",
    "till": "Caisse",
    "checkout": "Caisse",
    "billing": "Facturation",
    "invoice": "Facture",
    "receipt": "Reçu",
    "ticket": "Ticket",
    "voucher": "Bon",
    "coupon": "Coupon",
    "discount_code": "Code de remise",
    "promo_code": "Code promo",
    "barcode": "Code-barres",
    "qr_code": "Code QR",
    "sku": "SKU",
    "product_code": "Code produit",
    "item_code": "Code article",
    "reference": "Référence",
    "identifier": "Identifiant",
    "number": "Numéro",
    "serial": "Série",
    "batch": "Lot",
    "lot": "Lot",
    "expiry": "Expiration",
    "expiration": "Expiration",
    "shelf_life": "Durée de conservation",
    "best_before": "À consommer de préférence avant",
    "use_by": "À utiliser avant",
    "manufactured": "Date de fabrication",
    "production": "Production",
    "origin": "Origine",
    "source": "Source",
    "supplier": "Fournisseur",
    "vendor": "Vendeur",
    "brand": "Marque",
    "manufacturer": "Fabricant",
    "distributor": "Distributeur",
    "retailer": "Détaillant",
    "wholesaler": "Grossiste",
    "dealer": "Revendeur",
    "agent": "Agent",
    "representative": "Représentant",
    "sales_rep": "Représentant commercial",
    "account_manager": "Gestionnaire de compte",
    "relationship_manager": "Gestionnaire de relation",
    "customer_service": "Service client",
    "support": "Support",
    "help": "Aide",
    "assistance": "Assistance",
    "guidance": "Orientation",
    "instruction": "Instruction",
    "manual": "Manuel",
    "handbook": "Manuel",
    "guide": "Guide",
    "tutorial": "Tutoriel",
    "walkthrough": "Procédure pas à pas",
    "demonstration": "Démonstration",
    "explanation": "Explication",
    "description": "Description",
    "details": "Détails",
    "information": "Information",
    "data": "Données",
    "statistics": "Statistiques",
    "metrics": "Métriques",
    "analytics": "Analyses",
    "insights": "Insights",
    "intelligence": "Intelligence",
    "knowledge": "Connaissance",
    "expertise": "Expertise",
    "skill": "Compétence",
    "ability": "Capacité",
    "capability": "Capacité",
    "capacity": "Capacité",
    "volume": "Volume",
    "size": "Taille",
    "dimension": "Dimension",
    "measurement": "Mesure",
    "metric": "Métrique",
    "unit": "Unité",
    "scale": "Échelle",
    "level": "Niveau",
    "grade": "Grade",
    "class": "Classe",
    "type": "Type",
    "kind": "Genre",
    "sort": "Tri",
    "variety": "Variété",
    "version": "Version",
    "edition": "Édition",
    "release": "Version",
    "update": "Mise à jour",
    "upgrade": "Mise à niveau",
    "downgrade": "Rétrogradation",
    "rollback": "Retour arrière",
    "restore": "Restaurer",
    "recover": "Récupérer",
    "backup": "Sauvegarde",
    "archive": "Archive",
    "storage": "Stockage",
    "repository": "Dépôt",
    "database": "Base de données",
    "file": "Fichier",
    "document": "Document",
    "record": "Enregistrement",
    "entry": "Entrée",
    "element": "Élément",
    "component": "Composant",
    "part": "Partie",
    "piece": "Pièce",
    "module": "Module",
    "section": "Section",
    "segment": "Segment",
    "portion": "Portion",
    "fraction": "Fraction",
    "share": "Part",
    "allocation": "Allocation",
    "assignment": "Affectation",
    "distribution": "Distribution",
    "delivery": "Livraison",
    "shipment": "Expédition",
    "dispatch": "Expédition",
    "transport": "Transport",
    "transfer": "Transfert",
    "movement": "Mouvement",
    "flow": "Flux",
    "circulation": "Circulation",
    "rotation": "Rotation",
    "cycle": "Cycle",
    "sequence": "Séquence",
    "series": "Série",
    "chain": "Chaîne",
    "link": "Lien",
    "connection": "Connexion",
    "relationship": "Relation",
    "association": "Association",
    "partnership": "Partenariat",
    "collaboration": "Collaboration",
    "cooperation": "Coopération",
    "coordination": "Coordination",
    "synchronization": "Synchronisation",
    "alignment": "Alignement",
    "integration": "Intégration",
    "combination": "Combinaison",
    "mixture": "Mélange",
    "blend": "Mélange",
    "merge": "Fusion",
    "union": "Union",
    "join": "Rejoindre",
    "attach": "Attacher",
    "connect": "Connecter",
    "bind": "Lier",
    "tie": "Attacher",
    "fasten": "Attacher",
    "secure": "Sécuriser",
    "lock": "Verrouiller",
    "unlock": "Déverrouiller",
    "open": "Ouvrir",
    "close": "Fermer",
    "shut": "Fermer",
    "start": "Commencer",
    "begin": "Commencer",
    "initiate": "Initier",
    "launch": "Lancer",
    "activate": "Activer",
    "enable": "Activer",
    "turn_on": "Allumer",
    "switch_on": "Allumer",
    "power_on": "Allumer",
    "boot": "Démarrer",
    "startup": "Démarrage",
    "initialize": "Initialiser",
    "setup": "Configuration",
    "configure": "Configurer",
    "customize": "Personnaliser",
    "personalize": "Personnaliser",
    "adjust": "Ajuster",
    "modify": "Modifier",
    "change": "Changer",
    "alter": "Modifier",
    "refresh": "Actualiser",
    "reload": "Recharger",
    "restart": "Redémarrer",
    "reboot": "Redémarrer",
    "reset": "Réinitialiser",
    "clear": "Effacer",
    "empty": "Vide",
    "blank": "Vide",
    "null": "Nul",
    "none": "Aucun",
    "nothing": "Rien",
    "zero": "Zéro",
    "one": "Un",
    "two": "Deux",
    "three": "Trois",
    "four": "Quatre",
    "five": "Cinq",
    "six": "Six",
    "seven": "Sept",
    "eight": "Huit",
    "nine": "Neuf",
    "ten": "Dix",
    "hundred": "Cent",
    "thousand": "Mille",
    "million": "Million",
    "billion": "Milliard",
    "trillion": "Billion",
    "first": "Premier",
    "second": "Deuxième",
    "third": "Troisième",
    "last": "Dernier",
    "final": "Final",
    "initial": "Initial",
    "primary": "Primaire",
    "secondary": "Secondaire",
    "main": "Principal",
    "principal": "Principal",
    "major": "Majeur",
    "minor": "Mineur",
    "important": "Important",
    "critical": "Critique",
    "essential": "Essentiel",
    "necessary": "Nécessaire",
    "required": "Requis",
    "mandatory": "Obligatoire",
    "optional": "Optionnel",
    "voluntary": "Volontaire",
    "automatic": "Automatique",
    "manual": "Manuel",
    "custom": "Personnalisé",
    "default": "Par défaut",
    "standard": "Standard",
    "normal": "Normal",
    "regular": "Régulier",
    "common": "Commun",
    "typical": "Typique",
    "usual": "Habituel",
    "ordinary": "Ordinaire",
    "basic": "Basique",
    "simple": "Simple",
    "easy": "Facile",
    "difficult": "Difficile",
    "hard": "Dur",
    "complex": "Complexe",
    "complicated": "Compliqué",
    "advanced": "Avancé",
    "expert": "Expert",
    "professional": "Professionnel",
    "skilled": "Qualifié",
    "experienced": "Expérimenté",
    "qualified": "Qualifié",
    "certified": "Certifié",
    "licensed": "Licencié",
    "authorized": "Autorisé",
    "approved": "Approuvé",
    "verified": "Vérifié",
    "validated": "Validé",
    "confirmed": "Confirmé",
    "guaranteed": "Garanti",
    "assured": "Assuré",
    "safe": "Sûr",
    "protected": "Protégé",
    "guarded": "Gardé",
    "defended": "Défendu",
    "shielded": "Protégé",
    "covered": "Couvert",
    "included": "Inclus",
    "excluded": "Exclu",
    "added": "Ajouté",
    "removed": "Supprimé",
    "deleted": "Supprimé",
    "created": "Créé",
    "generated": "Généré",
    "produced": "Produit",
    "manufactured": "Fabriqué",
    "made": "Fait",
    "built": "Construit",
    "constructed": "Construit",
    "assembled": "Assemblé",
    "compiled": "Compilé",
    "processed": "Traité",
    "handled": "Traité",
    "managed": "Géré",
    "controlled": "Contrôlé",
    "operated": "Opéré",
    "executed": "Exécuté",
    "performed": "Effectué",
    "finished": "Fini",
    "done": "Fait",
    "prepared": "Préparé",
    "set": "Défini",
    "fixed": "Fixe",
    "stable": "Stable",
    "steady": "Stable",
    "constant": "Constant",
    "consistent": "Cohérent",
    "reliable": "Fiable",
    "dependable": "Fiable",
    "trustworthy": "Digne de confiance",
    "honest": "Honnête",
    "genuine": "Authentique",
    "authentic": "Authentique",
    "real": "Réel",
    "actual": "Réel",
    "true": "Vrai",
    "correct": "Correct",
    "right": "Correct",
    "proper": "Approprié",
    "appropriate": "Approprié",
    "suitable": "Approprié",
    "fitting": "Approprié",
    "matching": "Correspondant",
    "compatible": "Compatible",
    "harmonious": "Harmonieux",
    "balanced": "Équilibré",
    "equivalent": "Équivalent",
    "similar": "Similaire",
    "alike": "Semblable",
    "identical": "Identique",
    "same": "Même",
    "different": "Différent",
    "distinct": "Distinct",
    "separate": "Séparé",
    "individual": "Individuel",
    "personal": "Personnel",
    "private": "Privé",
    "public": "Public",
    "shared": "Partagé",
    "mutual": "Mutuel",
    "joint": "Conjoint",
    "combined": "Combiné",
    "united": "Uni",
    "together": "Ensemble",
    "apart": "À part",
    "alone": "Seul",
    "single": "Unique",
    "multiple": "Multiple",
    "several": "Plusieurs",
    "many": "Beaucoup",
    "few": "Peu",
    "some": "Quelques",
    "every": "Chaque",
    "each": "Chaque",
    "any": "Tout",
    "never": "Jamais",
    "always": "Toujours",
    "sometimes": "Parfois",
    "often": "Souvent",
    "rarely": "Rarement",
    "seldom": "Rarement",
    "frequently": "Fréquemment",
    "regularly": "Régulièrement",
    "constantly": "Constamment",
    "continuously": "Continuellement",
    "permanently": "En permanence",
    "temporarily": "Temporairement",
    "briefly": "Brièvement",
    "shortly": "Bientôt",
    "soon": "Bientôt",
    "later": "Plus tard",
    "earlier": "Plus tôt",
    "previously": "Précédemment",
    "formerly": "Anciennement",
    "currently": "Actuellement",
    "presently": "Actuellement",
    "now": "Maintenant",
    "immediately": "Immédiatement",
    "instantly": "Instantanément",
    "quickly": "Rapidement",
    "rapidly": "Rapidement",
    "fast": "Rapide",
    "slow": "Lent",
    "slowly": "Lentement",
    "gradually": "Graduellement",
    "progressively": "Progressivement",
    "incrementally": "Incrémentalement",
    "step_by_step": "Étape par étape",
    "phase_by_phase": "Phase par phase",
    "stage_by_stage": "Étape par étape",
    "level_by_level": "Niveau par niveau",
    "layer_by_layer": "Couche par couche",
    "piece_by_piece": "Pièce par pièce",
    "bit_by_bit": "Petit à petit",
    "little_by_little": "Petit à petit",
    "one_by_one": "Un par un",
    "side_by_side": "Côte à côte",
    "hand_in_hand": "Main dans la main",
    "face_to_face": "Face à face",
    "head_to_head": "Tête à tête",
    "back_to_back": "Dos à dos",
    "end_to_end": "De bout en bout",
    "top_to_bottom": "De haut en bas",
    "left_to_right": "De gauche à droite",
    "right_to_left": "De droite à gauche",
    "up_and_down": "Haut et bas",
    "in_and_out": "Entrer et sortir",
    "on_and_off": "Marche et arrêt",
    "yes_and_no": "Oui et non",
    "true_and_false": "Vrai et faux",
    "good_and_bad": "Bon et mauvais",
    "right_and_wrong": "Bien et mal",
    "black_and_white": "Noir et blanc",
    "day_and_night": "Jour et nuit",
    "hot_and_cold": "Chaud et froid",
    "big_and_small": "Grand et petit",
    "old_and_new": "Ancien et nouveau",
    "past_and_future": "Passé et futur",
    "here_and_there": "Ici et là",
    "now_and_then": "De temps en temps",
    "before_and_after": "Avant et après",
    "first_and_last": "Premier et dernier",
    "beginning_and_end": "Début et fin",
    "start_and_finish": "Début et fin",
    "open_and_close": "Ouvrir et fermer",
    "buy_and_sell": "Acheter et vendre",
    "give_and_take": "Donner et prendre",
    "come_and_go": "Aller et venir",
    "push_and_pull": "Pousser et tirer",
    "cut_and_paste": "Couper et coller",
    "copy_and_paste": "Copier et coller",
    "save_and_load": "Sauvegarder et charger",
    "import_and_export": "Importer et exporter",
    "input_and_output": "Entrée et sortie",
    "upload_and_download": "Télécharger et télécharger",
    "send_and_receive": "Envoyer et recevoir",
    "read_and_write": "Lire et écrire",
    "create_and_delete": "Créer et supprimer",
    "add_and_remove": "Ajouter et supprimer",
    "insert_and_delete": "Insérer et supprimer",
    "show_and_hide": "Afficher et masquer",
    "display_and_conceal": "Afficher et cacher",
    "reveal_and_cover": "Révéler et couvrir",
    "expose_and_protect": "Exposer et protéger",
    "lock_and_unlock": "Verrouiller et déverrouiller",
    "enable_and_disable": "Activer et désactiver",
    "activate_and_deactivate": "Activer et désactiver",
    "turn_on_and_off": "Allumer et éteindre",
    "switch_on_and_off": "Allumer et éteindre",
    "power_on_and_off": "Allumer et éteindre",
    "start_and_stop": "Démarrer et arrêter",
    "play_and_pause": "Jouer et pauser",
    "forward_and_backward": "Avant et arrière",
    "next_and_previous": "Suivant et précédent",
    "increase_and_decrease": "Augmenter et diminuer",
    "more_and_less": "Plus et moins",
    "plus_and_minus": "Plus et moins",
    "positive_and_negative": "Positif et négatif",
    "gain_and_loss": "Gain et perte",
    "profit_and_loss": "Profit et perte",
    "income_and_expense": "Revenu et dépense",
    "revenue_and_cost": "Revenu et coût",
    "sales_and_purchases": "Ventes et achats",
    "credit_and_debit": "Crédit et débit",
    "assets_and_liabilities": "Actifs et passifs",
    "equity_and_debt": "Capital et dette",

    // Order Queue translations
    "order_queue_list": "Liste d'attente des commandes",
    "waiting_time_minutes": "Temps d'attente (minutes)",
    "not_specified": "Non spécifié",
    "customer_queue_screen": "Écran de file d'attente client",
    "no_orders_in_queue": "Aucune commande en attente",
    "estimated_time": "Temps estimé",
    "elapsed_time": "Temps écoulé",
    "remaining_time": "Temps restant"
  }
};

const LanguageContext = createContext<LanguageContextType>({
  language: 'ar',
  setLanguage: () => {},
  t: (key: string) => key,
});

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<'ar' | 'en' | 'fr'>(() => {
    return getSettings().language || 'ar';
  });

  const setLanguage = (newLanguage: 'ar' | 'en' | 'fr') => {
    setLanguageState(newLanguage);
    const settings = getSettings();
    updateSettings({ ...settings, language: newLanguage });

    // Set the page direction based on language
    document.documentElement.dir = newLanguage === 'ar' ? 'rtl' : 'ltr';
  };

  // Function to get translated text
  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['ar']] || key;
  };

  // Initialize direction on page load
  useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};